Add "import" Function and "UNSAFE_NO_SANDBOX" Flag for Accessing Built-in Lua Objects & Functions
lunarmodules/LDoc pull request #359
Opened 2021-07-23 20:25 UTC by AntumDeluge

Hoping this is a more acceptable solution than #308.

This add an `import` function which is enabled with the `UNSAFE_NO_SANDBOX` command line flag & is used to access built-in Lua objects & functions within the `config.ld` file.

*Example config.ld:*
```lua
local print = import("print")
local string = import("string")

for _, s in ipairs({string.split("Hello world!")}) do
	print(s)
end

project = "foo"
title = "Bar"
file = {"init.lua"}
```

*Example execution:*
```
ldoc --UNSAFE_NO_SANDBOX .
```

2022-01-17 11:49 UTC, alerque commented
I would be okay dropping the use of `SCREAM_CASE`, but I think we should keep the urgent verbose tone with the words "unsafe" and a negative "no", so `--unsafe_no_sandbox`. The only other alternative might be to split this into two flags and require both, e.g. `--no-sandbox`, but require a `--unsafe` flag to enable unsafe feature(s). If we think there might be more than one we want to warn about like this perhaps that would be best.

2023-04-29 20:18 UTC, alerque requested changes
Having the option is fine, all in needs is a way to set it without screaming ;-)

https://github.com/lunarmodules/LDoc/pull/359#issuecomment-1014436358

2023-05-02 05:17 UTC, AntumDeluge commented
Changed `UNSAFE_NO_SANDBOX` to `unsafe_no_sandbox`.

2023-05-02 08:17 UTC, alerque approved these changes

2023-05-02 08:19 UTC, merged