Fix Icon Path
lunarmodules/LDoc pull request #361
Opened 2021-08-01 04:11 UTC by AntumDeluge

Fixes icon path when file path is nested.

2021-08-01 06:36 UTC, Tieske requested changes

2021-08-01 06:36 UTC, Tieske commented on ldoc.lua
> +	ldoc.icon_basename = path.basename(ldoc.icon)
the indentation is off here

2021-08-01 06:40 UTC, AntumDeluge commented on ldoc.lua
> +	ldoc.icon_basename = path.basename(ldoc.icon)
Fixed.

2021-08-01 06:51 UTC, Tieske approved these changes
Lgtm @alerque

2023-04-29 20:10 UTC, alerque approved these changes

2023-04-29 20:10 UTC, merged