Prettify function names
lunarmodules/LDoc pull request #382
Opened 2022-10-24 12:08 UTC by tommaisey

I find it very helpful to colorize function names in our code examples. This also helps beginners understand that `x()`, `x {}` and `x ''` are all function calls.

In the process of doing this I found that LDoc wasn't running successfully under Lua 5.1, so I fixed that.

Tests run and pass. Example from a module I'm working on called `fold`:

<img width="667" alt="Screenshot 2022-10-24 at 13 05 00" src="https://user-images.githubusercontent.com/2369921/197522183-0fcf2897-a4e2-43fa-a907-a227ac6f5c19.png">

2022-10-24 13:20 UTC, alerque requested changes
Thanks for taking the time to contribute! Next time I'd kind of rather split this sort of thing up into two PR's, one for each general concern, but since we're here and the commits at least are separate lets have a look.

2022-10-24 13:23 UTC, tommaisey commented on ldoc.lua
> +      local load = is_lua_51 and utils.load or (load or utils.load)
I don't imagine that would be a problem - after all, that's the purpose of `utils.load`, to be compatible with all versions. I was just hesitant to change any existing behaviour, but I think you're right.

I'll make a separate PR for this Lua 5.1 fix, and remove this commit. And in that PR I'll default to `utils.load`.

2022-10-28 14:20 UTC, tommaisey commented
What's the procedure for getting something merged and released, by the way?

2022-11-30 17:30 UTC, tommaisey commented
Any updates on that?

2022-11-30 20:44 UTC, alerque commented
I'm holding off merging new features until I figure out the release procedures here. I want to make sure we have a safe-haven release of sorts, then quite a few PRs are going to land at once.

2023-04-29 20:06 UTC, alerque commented
A safe-harbor release doesn't seem to make much sense, 1.4.6 is exactly that. Only a small handful of minor commits since then were done before the migration to LuaRocks and the Git HEAD version already has significant changes, so we'll just move on and make the next release a big one.

2023-04-29 20:06 UTC, merged