Replace many dead links with web.archive.org equivalants.
lunarmodules/ldoc pull request #397
Opened 2023-05-10 19:44 UTC by IoIxD

There was quite a few dead links, especially at the beginning. This PR replaces them with the most recent web.archive.org snapshot

2023-05-10 22:34 UTC, catwell commented
It would probably be better to replace them with the new links for those projects when they exist, especially when they are lunarmodules projects!

I.e.:

- https://keplerproject.github.io/luadoc/
- https://lunarmodules.github.io/luafilesystem/

The textui docs link (https://nilnor.github.io/textui/docs/) appears to work for me.

Using archive.org for z/OS might make sense, or we may just remove the reference.

2023-05-11 07:12 UTC, alerque requested changes
Much like @catwell suggested it would be much better to link to the new homes of these projects rather than to archived versions of their old homes. Even if the exact same page is not available we should adjust the references so that we link to current resources. If anything is really no longer available we should probably just rewrite the docs to avoid the reference and substitute something current or at least make sure it is a minor point.

Thanks for taking the time to contribute. Are you able to update this PR with current links?

2023-05-11 20:46 UTC, IoIxD commented
Swear it didn't work for me, but yeah I guess it does. Fixed.

2023-05-11 20:57 UTC, alerque requested changes

2023-05-11 20:57 UTC, alerque commented on manual.md
> +You can ship your own customized templates and style sheets with your [own project](http://nilnor.github.io/textui/docs/) (also see Graham Hannington's documentation for [Lua for z/OS](https://web.ar
GitHub Pages supports SSL:

```suggestion
You can ship your own customized templates and style sheets with your [own project](https://nilnor.github.io/textui/docs/) (also see Graham Hannington's documentation for [Lua for z/OS](https://web.archive.org/web/20191231114636/http://lua4z.com/doc/)).
```

2023-05-13 00:08 UTC, IoIxD reviewed
Done.

2023-05-13 05:12 UTC, alerque approved these changes
Thanks for the contribution.

2023-05-13 05:12 UTC, merged